### ISSUE TITLE
Error with Fuseki in Rudolf with: /api/3/cubes

### ISSUE THREAD

**Issue by schmaluk** [openbudgets/rudolf#10]
Hi, Im getting this error when calling /api/3/cubes.
http://eis-openbudgets.iais.fraunhofer.de/api/3/cubes
But other urls do work: http://eis-openbudgets.iais.fraunhofer.de/api/3/info/budget-thessaloniki-expenditure-2011/package

`[2016-07-04 17:37:09] production.ERROR: EasyRdf_Exception: HTTP request for SPARQL query failed: Error 400: Parse error: 
PREFIX rdfs: http://www.w3.org/2000/01/rdf-schema# PREFIX qb: http://purl.org/linked-data/cube# PREFIX skos: http://www.w3.org/2004/02/skos/core# PREFIX rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns# PREFIX xro: http://purl.org/xro/ns# SELECT (SAMPLE(?name) AS ?name) WHERE { ?dataset a qb:DataSet . BIND (CONCAT(REPLACE(str(?dataset), '^.*(#|/)', ""), '__', SUBSTR(MD5(STR(?dataset)),1,5)) AS ?name) } GROUP BY ?dataset

Variable used when already in-scope: ?name in ((AGG ?.0 SAMPLE(?name)) AS ?name)

Fuseki - version 2.4.0 (Build date: 2016-05-10T11:59:39+0000)
 in /var/www/rudolf/vendor/easyrdf/easyrdf/lib/EasyRdf/Sparql/Client.php:290
Stack trace:
#0 /var/www/rudolf/vendor/easyrdf/easyrdf/lib/EasyRdf/Sparql/Client.php(120): EasyRdf_Sparql_Client->request('query', 'PREFIX rdfs: <h...')
#1 /var/www/rudolf/app/Model/CubesResult.php(40): EasyRdf_Sparql_Client->query('PREFIX rdfs: <h...')
#2 /var/www/rudolf/app/Model/CubesResult.php(20): App\Model\CubesResult->load()
#3 /var/www/rudolf/app/Http/Controllers/Api/CubesController.php(20): App\Model\CubesResult->__construct()
#4 [internal function]: App\Http\Controllers\Api\CubesController->index('3')
#5 /var/www/rudolf/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(80): call_user_func_array(Array, Array)
#6 /var/www/rudolf/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(146): Illuminate\Routing\Controller->callAction('index', Array)
#7 /var/www/rudolf/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(94): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\Api\CubesController), Object(Illuminate\Routing\Route), 'index')
#8 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#9 /var/www/rudolf/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#11 /var/www/rudolf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#12 /var/www/rudolf/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(96): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#13 /var/www/rudolf/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(54): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\Api\CubesController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'index')
#14 /var/www/rudolf/vendor/laravel/framework/src/Illuminate/Routing/Route.php(174): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\Http\Contro...', 'index')
#15 /var/www/rudolf/vendor/laravel/framework/src/Illuminate/Routing/Route.php(140): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#16 /var/www/rudolf/vendor/laravel/framework/src/Illuminate/Routing/Router.php(724): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#18 /var/www/rudolf/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#20 /var/www/rudolf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#21 /var/www/rudolf/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#22 /var/www/rudolf/vendor/laravel/framework/src/Illuminate/Routing/Router.php(699): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#23 /var/www/rudolf/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#24 /var/www/rudolf/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(246): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#25 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http{closure}(Object(Illuminate\Http\Request))
#26 /var/www/rudolf/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#27 /var/www/rudolf/vendor/barryvdh/laravel-cors/src/HandleCors.php(34): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#28 [internal function]: Barryvdh\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /var/www/rudolf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#30 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#31 /var/www/rudolf/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#32 /var/www/rudolf/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#33 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /var/www/rudolf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#35 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#36 /var/www/rudolf/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#37 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#38 /var/www/rudolf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#39 /var/www/rudolf/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#40 /var/www/rudolf/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#41 /var/www/rudolf/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#42 {main}`

**Comment by larjohn** [comment]
Must have been solved with beec4a1a3f48b6fbfe2deca6df7c1325a15d4994

@mlukasch can you try?

**Comment by schmaluk** [comment]
Thanks for the quick fix. It works. 
Getting this response back from http://eis-openbudgets.iais.fraunhofer.de/api/3/cubes:
{"data":[{"name":"reserves__09751"},{"name":"budget-of-the-european-union-2014__a6fcb"},{"name":"budget-kilkis-expenditure-2010__7b804"},{"name":"budget-thessaloniki-expenditure-2011__803aa"},{"name":"global"}],"status":"ok"}
