### ISSUE TITLE
prefixes aren't defined for this query

### ISSUE THREAD

**Issue by schmaluk** [openbudgets/rudolf#16]
Hello,
so now the Search-API of OS is used in our OS-Viewer:
http://eis-openbudgets.iais.fraunhofer.de/viewer/
This cannot work of course atm since the datasets are missing in our Production Triplestore.
But since Im not so sure about the reason here, I'll submit this issue even so to be safe.
This URL is called by our OS-Viewer:
http://eis-openbudgets.iais.fraunhofer.de/api/3/cubes/583b10ad15f2e7f078afd3431c2c09ea:test/model
and a 500 is returned by Rudolf. Having found this in the logs:

[2016-07-21 11:30:18] production.ERROR: RangeException: The prefixes 583b10ad15f2e7f078afd3431c2c09ea aren't defined for this query. in /var/www/rudolf/vendor/benestar/asparagus/src/UsageValidator.php:116
Stack trace:
#0 /var/www/rudolf/vendor/benestar/asparagus/src/UsageValidator.php(109): Asparagus\UsageValidator->validatePrefixes()
#1 /var/www/rudolf/vendor/benestar/asparagus/src/QueryBuilder.php(417): Asparagus\UsageValidator->validate()
#2 /var/www/rudolf/app/Model/BabbageModelResult.php(62): Asparagus\QueryBuilder->getSPARQL()

Thanks a lot and sorry, should the reason for this be, just that the datasets are not there.

**Comment by larjohn** [comment]
Is there such a dataset?

Here are the available cubes:

http://eis-openbudgets.iais.fraunhofer.de/api/3/cubes

**Comment by schmaluk** [comment]
No there isnt. That is then the reason for the issue. When OKI provides the upload to our pipeline next week, we will have datasets which are also in the OS-conductor.
