### ISSUE TITLE
ErrorMessage during startup

### ISSUE THREAD

**Issue by schmaluk** [openbudgets/rudolf#17]
Hello @larjohn,
during Installation I receive this errorMessage from Rudolf on the Fhg-server:

rudolf_1                   | Updating Rudolf from remote Git-repo
rudolf_1                   | From https://github.com/openbudgets/rudolf
rudolf_1                   |  \* branch            master     -> FETCH_HEAD
rudolf_1                   | Already up-to-date.
rudolf_1                   | Installing Rudolf
rudolf_1                   | Do not run Composer as root/super user! See https://getcomposer.org/root for details
rudolf_1                   | Loading composer repositories with package information
Updating dependencies (including require-dev)  
rudolf_1                   | Your requirements could not be resolved to an installable set of packages.
rudolf_1                   | 
rudolf_1                   |   Problem 1
rudolf_1                   |     - The requested package zhenbo/parser could not be found in any version, there may be a typo in the package name.
rudolf_1                   | 
rudolf_1                   | Potential causes:
rudolf_1                   |  - A typo in the package name
rudolf_1                   |  - The package is not available in a stable-enough version according to your minimum-stability setting
rudolf_1                   |    see https://getcomposer.org/doc/04-schema.md#minimum-stability for more details.
rudolf_1                   | 
rudolf_1                   | Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

Do I need to change sthg on my side?
Thanks

**Comment by larjohn** [comment]
Hey @mlukasch 
can you check with the latest commit?
Please report back.

**Comment by schmaluk** [comment]
@larjohn Thanks a lot. Its working again: http://eis-openbudgets.iais.fraunhofer.de/api/3/cubes
