### ISSUE TITLE
Problem with OS-Viewer & OS-Explorer

### ISSUE THREAD

**Issue by schmaluk** [openbudgets/rudolf#18]
Hello @larjohn,
I have updated to the latest Docker images of OS-Viewer & OS-Explorer as well as rebuilt Rudolf from master.
Im getting an errormessage in the Browser though when accesing:
http://eis-openbudgets.iais.fraunhofer.de/viewer
It seems that this URL is called but returning a 504 Gateway TImeout.
http://eis-openbudgets.iais.fraunhofer.de/search/package?size=10000

Also the same for the OS-Explorer:
http://eis-openbudgets.iais.fraunhofer.de/explorer
Typing "Ag" in the Search-field results in a request:
http://eis-openbudgets.iais.fraunhofer.de/search/package?q=%22Ag%22&size=10000
But getting a 504 Gateway TImeout back.

Thank you

**Comment by larjohn** [comment]
The triple store needed to change, as it pointed to the old Fuseki instance. Also, if these operations time out, you can try out the new commands described in README.md
