### ISSUE TITLE
/models and /facts endpoints failing with ErrorException

### ISSUE THREAD

**Issue by pierorex** [openbudgets/rudolf#19]
Rudolf endpoint: http://eis-openbudgets.iais.fraunhofer.de/api/3/cubes
Tested datasets: bonn-budget-2016__6cf09, aragon-2015-income__c413b

When I try to get /model from those datasets using that rudolf installation (http://eis-openbudgets.iais.fraunhofer.de/api/3/cubes/aragon-2015-income__c413b/model), it fails with something like this:
![rudolf-error-model](https://cloud.githubusercontent.com/assets/9373636/20177065/269ee494-a74b-11e6-896e-509c901bf5b4.png)

And when trying with the /facts route:
![rudolf-error-facts](https://cloud.githubusercontent.com/assets/9373636/20177141/7e8cf3bc-a74b-11e6-9285-e8d00e163658.png)

But then if I try with some other datasets, like budget-katerini-revenue-2016__235c7, it all works perfectly.

Anyone has some ideas as of why is this happening?

PD: the server is updated to RUDOLF's latest commit.

**Comment by larjohn** [comment]
This is due to http://data.openbudgets.eu/resource/dataset/aragon-2015-income missing a title property (http://purl.org/dc/terms/title). While a friendly error message would be a lot better, still, the dataset need this attribute to correctly work.

You can get in touch with @mlukasch on how you could update this with the least effort.

**Comment by schmaluk** [comment]
I have re-imported the graph for "aragon-2015-income" and now I see the property for title here: http://data.openbudgets.eu/resource/datasets/aragon-income-2015
Maybe some other properties are missing then?
Could you please have look too @fathoni ? Thanks

**Comment by schmaluk** [comment]
@fathoni is working on a fix for the issue on the Aragon dataset. there has been some mismatch in the naming, for example:
http://data.openbudgets.eu/resource/datasets/aragon-2015-income should be
http://data.openbudgets.eu/resource/dataset/aragon-2015-income
Thanks for reporting & having a look though.

**Comment by fathoni** [comment]
Hi all, fixed datasets are ready for Aragon and I will need @mlukasch to load these datasets to our triple store tomorrow.

**Comment by schmaluk** [comment]
Thanks @fathoni @pierorex http://eis-openbudgets.iais.fraunhofer.de/api/3/cubes/aragon-2015-expenditure__22925/model is working. Closing the ticket.
