### ISSUE TITLE
Mr.PlaceHolder as author in Explorer

### ISSUE THREAD

**Issue by schmaluk** [openbudgets/rudolf#23]
Sorry @larjohn to come up with another issue.
At the moment we see in the Explorer "Mr. Placeholder":
http://eis-openbudgets.iais.fraunhofer.de/explorer/
as author of the datasets due to Rudolf returning this information: 
```
"package":{"author":"Place Holder <place.holder@not.shown>"
```
http://eis-openbudgets.iais.fraunhofer.de/search/package?size=50
Would it be possible to substitute this by some more meaningful data? Or should the author information should get hide in the frontend (by substituting some of the JS-files in OS-Explorer-app)?

**Comment by larjohn** [comment]
I am not sure how trivial would be to update all the datasets with a standard authors triple.

**Comment by schmaluk** [comment]
Might be that something like: n/a or "not available" would be more meaningful to the user(?) as default null-value. So an update of the datasets themselves could be avoided.

**Comment by larjohn** [comment]
This will be resolved this weekend.

**Comment by larjohn** [comment]
A new config option, for default contributor, is provided. Please also update the configuration file with newer options.
