### ISSUE TITLE
FatalThrowableError in QueryBuilder.php line 66

### ISSUE THREAD

**Issue by liyakun** [openbudgets/rudolf#24]
After updating rudolf with last commit, this error happens when visit "http://eis-openbudgets.iais.fraunhofer.de/search/package". @larjohn Do you may know why this happen? thanks.

**Comment by larjohn** [comment]
This is caused by the outdated sparql.php config file.

I can update this tonight or you can just copy over the default and only modify the endpoint

**Comment by liyakun** [comment]
@larjohn it would be great that you update the config file on the repository, then I will just pull the last commit in the Dockerfile. Thank you.

**Comment by larjohn** [comment]
It's already committed here: https://github.com/openbudgets/integration/commit/7abaca5800adf59b2ea6c4cc7a4c02b12b71f238

**Comment by liyakun** [comment]
@larjohn thank you!
