### ISSUE TITLE
Facts not working for some datasets

### ISSUE THREAD

**Issue by larjohn** [openbudgets/rudolf#25]
http://eis-openbudgets.iais.fraunhofer.de/api/3/cubes/budget_mairie18__994e0/facts?pagesize=20

**Comment by larjohn** [comment]
http://ws307.math.auth.gr/rudolf/public/api/3/cubes/aragon-2014-expenditure__0377c/facts?pagesize=3000

**Comment by larjohn** [comment]
With this query:
```

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xro: <http://purl.org/xro/ns#>

SELECT DISTINCT ?attribute (GROUP_CONCAT (distinct ?labels;
	separator ='||') AS ?labels) ?attachment (SAMPLE (?_propertyType) AS ?propertyType) ?shortName ?dataset WHERE {
	?dsd qb:component ?component .
	?dataset a qb:DataSet ;
		qb:structure ?dsd .
	?component ?componentProperty ?attribute .
	?componentProperty rdfs:subPropertyOf qb:componentProperty .
	OPTIONAL {
		?attribute rdfs:label ?label .
	}
	OPTIONAL {
		?component qb:componentAttachment ?attachment .
	}
	OPTIONAL {
		?attribute a ?_propertyType .
		FILTER (?_propertyType in (qb:CodedProperty, qb:MeasureProperty, qb:DimensionProperty))
	}
	FILTER (?name = 'budget_mairie18__994e0') BIND (REPLACE (str (?attribute), '^.*(#|/)', "") AS ?shortName) BIND (CONCAT (REPLACE (str (?dataset), '^.*(#|/)', ""), '__', SUBSTR (MD5 (STR (?dataset)),1,5)) AS ?name) BIND (CONCAT (LANG (?label),' =', ?label) AS ?labels)
}
GROUP BY ?attribute ?shortName ?attachment ?dataset
```

you can see that the currency dimension is a Measure property. But the following query proves that it never takes any value:

```
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xro: <http://purl.org/xro/ns#>

SELECT ?binding_1af03 ?observation WHERE {
	?observation <http://data.openbudgets.eu/ontology/dsd/attribute/currency> ?binding_1af03 ;  
<http://purl.org/linked-data/cube#dataSet> <http://data.openbudgets.eu/resource/dataset/budget_mairie18> ; 
<http://www.w3.org/1999/02/22-rdf-syntax-ns#type> qb:Observation .
	
}
ORDER BY ASC (?observation)
LIMIT 20 OFFSET 0

```

**Comment by skarampatakis** [comment]
For some reason, dimensions are multiple times defined

http://data.openbudgets.eu/sparql?default-graph-uri=&query=select+%3Fs+%3Fp+%3Fo+%3Fp2+%3Fo3+where+%7B%0D%0A%3Fs+%3Fp+%3Fo+.%0D%0A%3Fo+%3Fp2+%3Fo3%0D%0Avalues+%3Fs+%7B%3Chttp%3A%2F%2Fdata.openbudgets.eu%2Fontology%2Fdsd%2Fbudget_mairie18%3E%7D%0D%0A%7D%0D%0Aorder+by+%3Fo3&should-sponge=&format=text%2Fhtml&timeout=0&debug=on

```
select ?dsd ?prop1 ?obj1 ?prop2 ?obj2 
where {
?dsd ?prop1 ?obj1 .
?obj1 ?prop2 ?obj2 .
values ?dsd {<http://data.openbudgets.eu/ontology/dsd/budget_mairie18>}
}
order by ?obj2
```

http://data.openbudgets.eu/ontology/dsd/budget_mairie18

So my guess is that somehow these triples where not deleted when the hook was re-run. 

@liyakun What is the workflow on the server when somebody re runs a pipeline from the hook?

**Comment by skarampatakis** [comment]
@larjohn the problem is that the currency is attached as attribute on the measure and not on the observation. So it is a modeling problem. 

http://data.openbudgets.eu/ontology/dsd/budget_mairie18/measure/Mandate_Titre_apres_regul

Is this data coming from the latest update of the FDP2RDF pipeline?

**Comment by fathoni** [comment]
Hi @skarampatakis , This dataset was generated using FDP2RDF pipeline using the hook last Wednesday. It may not be run from the latest FDP2RDF pipeline.

**Comment by skarampatakis** [comment]
Then I would suggest to firstly resolve https://github.com/openbudgets/pipeline-fragments/issues/28 and then re-check. Previous pipeline had some serious modeling problems, like the one mentioned above, which I doubt if any client app could deal with. 

Please also check the dataset updating workflow. 
@marek-dudas, @liyakun 
does datasets from the FDP2RDF pipeline upload on a discrete graph? What happens when someone re-runs the hook?

**Comment by marek-dudas** [comment]
The target graph should be cleared on Virtuoso before the new one is uploaded when someone re-runs the hook. I.e. the graph is rewritten each time the hook is re-run.

Also, the current version of the pipeline is finally working on Fraunhofer server, so you may start testing it.

**Comment by skarampatakis** [comment]
> The target graph should be cleared on Virtuoso

Is this triggered by the pipeline already, or it should be done manually? 

As long as I am concerned, at least for Virtuoso, when you upload the same triples for the same graph, it does not automatically clears the previous one. So you may end up with multiple non unique triples.

**Comment by marek-dudas** [comment]
It is triggered by the pipeline, sorry for the confusion. (I said "should" because I have not explicitly tested it, but it is a standard option in the corresponding LP component, so I think it should work.)

**Comment by skarampatakis** [comment]
Tested and seems to be ok. Also I found that the pipeline indeed clears the previous graph. Thank you. 

@larjohn can you confirm that issue can be closed?

**Comment by larjohn** [comment]
@skarampatakis for the specific datasets it may be closed - this does not guarantee that it won't be open if another datasets misbehaves
